### ISSUE TITLE
Division by Zero

### ISSUE THREAD

**Issue by ryanlelek** [chrismeyersfsu/python-card_scan#2]
I'm receiving a "ZeroDivisionError: float division by zero" exception.
This is confirmed to be initiated from line 43 of cv_utils.py.

![python_card_scan_division_by_zero](https://f.cloud.github.com/assets/329460/1527910/17fa2426-4bff-11e3-9fce-3496c91a3228.png)

``` python
# Original Line 43
return cv.DotProduct(tmp1, tmp2) /  (cv.Sum(norm1)[0]*cv.Sum(norm2)[0])**0.5

# Edited - Prevents Crash (may affect card recognition)
return cv.DotProduct(tmp1, tmp2) /  (((cv.Sum(norm1)[0]*cv.Sum(norm2)[0])**0.5) + 0.1)
```

Will continue debugging (been at it for about 8 hours trying to get one card to recognize).

OS: Clean Lubuntu 12.10
Using Python v2.7.2 (Python 3.x throws a syntax error)

Ryan

**Comment by ryanlelek** [comment]
Made progress and things are working on another machine.
Going to test further to see what the issue was.
Will update with more info soon

Ryan

**Comment by chrismeyersfsu** [comment]
old
